version: "3"
services:
  comments-blog:
    image: dudakp/comments-blog
    container_name: comments-blog
    volumes:
    - .:/app
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: ["npm", "run", "develop"]
networks:
  default:
    external:
      name: blog
